// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwsxejamyiztltxpcplg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3c3hlamFteWl6dGx0eHBjcGxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzODI5NDUsImV4cCI6MjA2OTk1ODk0NX0.73zOog1Zs0m1NDl-pphhecRQq951M5euv8P3-NnRZSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});